kafka:
  hosts:
  - "192.168.1.68:9092"
  topics:
    portscan: "scanner.ports"
    enriched: "scanner.whois"
  client:
    groupid: "whois-cli-1"

zookeeper:
  path: "192.168.1.68:2181"

geoip:
  path: "/home/vitorfernandes/tools/GeoLiteCity.dat"
